### ISSUE TITLE
Red Light/Green Light is client side

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/cScripts#546]
The red light and green lights are only client side as of now. If possible, making this a server-side notification (and extending it) will assist in issues of everyone yelling "ITS RED LIGHT" when Joe Trooper loaded in before them and have already cleared their red light.

**Comment by RaynorD** [comment]
Which aircraft?

**Comment by Robot-Panda15** [comment]
Not on aircraft, it's the operation notification at the beginning of the ops, when it gives you the red light info

**Comment by ColdEvul** [comment]
The OP notification is trigger on mission start only and is just a funny blur today.
The slight delay you might experience whould not be overcome by running it server sided. cause it is still shown on the client and is based when the mission is triggerd. Much like how it is done today. 

On another note:
The red light green light system tho is depricated since way back cause it today serve no real purpes cause all systems are already loaded when you see the UI.
